### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by nufuk** [blueimp/mailhog-node#1]
While using the function getHTML or getText as described in the README.md I get the following error. I can only use the unformated ouput of the query.

```
TypeError: Cannot read property '1' of null
    at getContentPart (/home/norbert/tools/calponia/acceptance-tests/node_modules/mailhog/mailhog.js:72:50)
    at Object.getText (/home/norbert/tools/calponia/acceptance-tests/node_modules/mailhog/mailhog.js:100:14)
....
```

**Comment by nufuk** [comment]
using this example:
```
mailhog.search('example.org').then(function (result) {
  for (let mail of result.items) {
    console.log(mailhog.getText(mail))
  }
}).catch(function (error) {
  console.error(error)
})
```

**Comment by n0v1** [comment]
I get the same error when using the `getLatests` function

```javascript
mailhog.getLatest('sender@example.com', true, 'from')
```

The problem seems to be that the `Content-Type` header field does not contain a charset. It's just `"text/plain"` inside the `getContentPart` function. So the RegExp `/\bcharset=([\w_-]+)(?:;|$)/.exec(type)` will return `null` and not an array as expected.
